name: Main README TOC generator

on:
  workflow_dispatch:

jobs:
  generate-toc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: clone toc git repo
        run: git clone https://github.com/kisstamasj/toc-generator.git
        shell: bash
      - name: install deps
        run: cd ./toc-generator && yarn install
        shell: bash
      - name: make executeable
        run: chmod +x ./toc-generator/src/index.js
        shell: bash
      - name: run README.md generator
        run: ./toc-generator/src/index.js -F ./ -R ./README.md
        shell: bash
      - name: show result
        run: cat README.md
        shell: bash
